In [46]:
print("all okay nn" )

all okay nn


In [47]:
from sklearn.preprocessing import OneHotEncoder
import numpy


In [48]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]       

In [49]:

tokens = [sentence.lower().split() for sentence in documents]
print(tokens)


[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]


In [50]:
all_words = [[word] for sentence in tokens for word in sentence]
print(all_words)


[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket']]


In [51]:
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(all_words)
print("vocabulary:", encoder.categories_[0])



vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [52]:
print("tokens",tokens)

tokens [['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]


In [53]:
for sentence in tokens:
    print(sentence)

['people', 'watch', 'movie']
['people', 'watch', 'cricket']
['people', 'like', 'movie']
['people', 'like', 'cricket']


In [54]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print(sentence)
    print("encoded sentence: \n", encoded_sentence)

['people', 'watch', 'movie']
encoded sentence: 
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
['people', 'watch', 'cricket']
encoded sentence: 
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
['people', 'like', 'movie']
encoded sentence: 
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
['people', 'like', 'cricket']
encoded sentence: 
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
